---
all:
  vars:
    ansible_user: gaidar
  children:
    elasticstack:
      hosts:
        elasticsearch:
          ansible_host: 158.160.58.236
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
        filebeat:
          ansible_host: 51.250.90.223
          deb_package: filebeat-8.17.1-amd64.deb
          elastic_service: filebeat.service
        logstash:
          ansible_host: 89.169.139.117
          deb_package: logstash-8.17.1-amd64.deb
          elastic_service: logstash.service
        kibana:
          ansible_host: 51.250.69.227
          deb_package: kibana-8.17.1-amd64.deb
          elastic_service: kibana.service
