---
all:
  vars:
    ansible_user: gaidar
  children:
    elasticstack:
      hosts:
        elasticsearch:
          ansible_host: 158.160.62.238
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
        logstash:
          ansible_host: 158.160.60.23
          deb_package: logstash-8.17.1-amd64.deb
          elastic_service: logstash.service
        kibana:
          ansible_host: 158.160.46.115
          deb_package: kibana-8.17.1-amd64.deb
          elastic_service: kibana.service
        filebeat:
          ansible_host: 158.160.47.47
          deb_package: filebeat-8.17.1-amd64.deb
          elastic_service: filebeat.service
