---
all:
  vars:
    ansible_user: gaidar
  children:
    elasticstack:
      hosts:
        elasticsearch-hot:
          ansible_host: 158.160.48.71
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-hot
          node_roles: master,data_content,data_hot  
        elasticsearch-warm:
          ansible_host: 158.160.36.211
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-warm
          node_roles: master,data_warm
        logstash:
          ansible_host: 158.160.60.23
          deb_package: logstash-8.17.1-amd64.deb
          elastic_service: logstash.service
        kibana:
          ansible_host: 158.160.39.152
          deb_package: kibana-8.17.1-amd64.deb
          elastic_service: kibana.service
        filebeat:
          ansible_host: 158.160.47.47
          deb_package: filebeat-8.17.1-amd64.deb
          elastic_service: filebeat.service



    # container_name: es-hot
    # environment:
    #   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

      
    # container_name: es-warm
    # environment:
    #   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"