---
all:
  vars:
    ansible_user: gaidar
    # ansible_password: mvsadmin
    # ansible_become: yes
    # ansible_become_password: mvsadmin
  children:
    elasticstack:
      hosts:
        elasticsearch-hot:
          ansible_host: 51.250.15.193
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-hot
          node_roles: master,data_content,data_hot  
        elasticsearch-warm:
          ansible_host: 62.84.112.151
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-warm
          node_roles: master,data_warm
        logstash:
          ansible_host: 51.250.2.60
          deb_package: logstash-8.17.1-amd64.deb
          elastic_service: logstash.service
        kibana:
          ansible_host: 84.201.128.210
          deb_package: kibana-8.17.1-amd64.deb
          elastic_service: kibana.service
        filebeat:
          ansible_host: 84.252.131.68
          deb_package: filebeat-8.17.1-amd64.deb
          elastic_service: filebeat.service
