---
all:
  vars:
    ansible_user: gaidar
    ansible_password: mvsadmin
    ansible_become: yes
    ansible_become_password: mvsadmin
  children:
    elasticstack:
      hosts:
        elasticsearch-hot:
          ansible_host: 192.168.3.223
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-hot
          node_roles: master,data_content,data_hot  
        elasticsearch-warm:
          ansible_host: 192.168.3.224
          deb_package: elasticsearch-8.17.1-amd64.deb
          elastic_service: elasticsearch.service
          node_name: es-warm
          node_roles: master,data_warm
        # logstash:
        #   ansible_host: 158.160.60.23
        #   deb_package: logstash-8.17.1-amd64.deb
        #   elastic_service: logstash.service
        kibana:
          ansible_host: 192.168.3.226
          deb_package: kibana-8.17.1-amd64.deb
          elastic_service: kibana.service
        # filebeat:
        #   ansible_host: 158.160.47.47
        #   deb_package: filebeat-8.17.1-amd64.deb
        #   elastic_service: filebeat.service
