#cloud-config
users:
  - name: gaidar
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${vms_ssh_root_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - wget
  - curl
  - apt-transport-https
runcmd:
  - wget https://artifacts.elastic.co/downloads/logstash/logstash-8.17.1-amd64.deb
  - dpkg -i logstash-8.17.1-amd64.deb
  - apt update
  - apt -y install logstash
  - systemctl enable logstash.service
  - systemctl start logstash.service
